# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatemodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='process',
        ),
        migrations.RemoveField(
            model_name='projectstatemodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='subprocessmodel',
            name='process',
        ),
        migrations.DeleteModel(
            name='EstimateModel',
        ),
        migrations.DeleteModel(
            name='ProcessModel',
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
        migrations.DeleteModel(
            name='ProjectStateModel',
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
        migrations.DeleteModel(
            name='SubProcessModel',
        ),
    ]
