# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_auto_20170824_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='sampling_date',
            field=models.DateTimeField(verbose_name='\u53d6\u6837\u65f6\u95f4'),
        ),
    ]
