# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0004_auto_20170824_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatusTitleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6807\u9898')),
                ('date', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='\u65e5\u671f')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u72b6\u6001\u6807\u9898',
                'verbose_name_plural': '\u9879\u76ee\u72b6\u6001\u6807\u9898',
            },
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee'),
        ),
    ]
