# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_auto_20170825_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgressDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5bb9')),
                ('date', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='\u65e5\u671f')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u8fdb\u5ea6\u8be6\u60c5',
                'verbose_name_plural': '\u9879\u76ee\u8fdb\u5ea6\u8be6\u60c5',
            },
        ),
    ]
