# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0006_projectprogressdetailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspectionReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u540d\u79f0')),
                ('addr', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5730\u5740')),
                ('date', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='\u65e5\u671f')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_report', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u8d28\u68c0\u62a5\u544a',
                'verbose_name_plural': '\u8d28\u68c0\u62a5\u544a',
            },
        ),
    ]
