# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0007_qualityinspectionreportmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalExperimentReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u540d\u79f0')),
                ('addr', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5730\u5740')),
                ('date', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='\u65e5\u671f')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formal_experiment', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u6b63\u5f0f\u5b9e\u9a8c\u62a5\u544a',
                'verbose_name_plural': '\u6b63\u5f0f\u5b9e\u9a8c\u62a5\u544a',
            },
        ),
        migrations.CreateModel(
            name='PreExperimentReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u540d\u79f0')),
                ('addr', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5730\u5740')),
                ('date', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='\u65e5\u671f')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_experiment', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u9884\u5b9e\u9a8c\u62a5\u544a',
                'verbose_name_plural': '\u9884\u5b9e\u9a8c\u62a5\u544a',
            },
        ),
        migrations.RenameField(
            model_name='samplemodel',
            old_name='mark',
            new_name='remark',
        ),
        migrations.AddField(
            model_name='qualityinspectionreportmodel',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='qualityinspectionreportmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspection', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee'),
        ),
    ]
