# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0008_auto_20170825_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatemodel',
            name='logistics_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7269\u6d41\u8bc4\u4ef7'),
        ),
        migrations.AlterField(
            model_name='estimatemodel',
            name='logistics_satisfactory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7269\u6d41\u6ee1\u610f'),
        ),
        migrations.AlterField(
            model_name='estimatemodel',
            name='logistics_star',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7269\u6d41\u661f\u7ea7'),
        ),
        migrations.AlterField(
            model_name='estimatemodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='estimatemodel',
            name='service_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u670d\u52a1\u5546\u8bc4\u4ef7'),
        ),
        migrations.AlterField(
            model_name='estimatemodel',
            name='service_satisfactory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u670d\u52a1\u5546\u6ee1\u610f'),
        ),
        migrations.AlterField(
            model_name='estimatemodel',
            name='service_star',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u670d\u52a1\u5546\u661f\u7ea7'),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='apply_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9002\u7528\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7535\u5b50\u90ae\u4ef6'),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6d41\u7a0b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u624b\u673a/\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6d41\u7a0b\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='service_provider.ProcessModel', verbose_name='\u6d41\u7a0b'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='sample_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6837\u672c\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='sampling_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53d6\u6837\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='sampling_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u53d6\u6837\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7269\u79cd'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='test_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u68c0\u6d4b\u6307\u6807'),
        ),
        migrations.AlterField(
            model_name='projectstatemodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u751f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='projectstatemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u72b6\u6001\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='projectstatemodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6837\u672c\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='grouping',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5206\u7ec4'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6837\u672c\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='storage_medium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4fdd\u5b58\u4ecb\u8d28'),
        ),
        migrations.AlterField(
            model_name='subprocessmodel',
            name='cycle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9884\u8ba1\u5468\u671f'),
        ),
        migrations.AlterField(
            model_name='subprocessmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7535\u5b50\u90ae\u4ef6'),
        ),
        migrations.AlterField(
            model_name='subprocessmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5b50\u6d41\u7a0b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='subprocessmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u624b\u673a/\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='subprocessmodel',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocess', to='service_provider.ProcessModel', verbose_name='\u6d41\u7a0b'),
        ),
        migrations.AlterField(
            model_name='subprocessmodel',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5b50\u6d41\u7a0b\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='subprocessmodel',
            name='start_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5f00\u59cb\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='subprocessmodel',
            name='stop_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7ed3\u675f\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='subprocessmodel',
            name='update_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u66f4\u65b0\u72b6\u6001'),
        ),
    ]
