# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0009_auto_20170825_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstatemodel',
            old_name='name',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='projectstatustitlemodel',
            old_name='title',
            new_name='content',
        ),
        migrations.AddField(
            model_name='estimatemodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u53ef\u7528\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='formalexperimentreportmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u53ef\u7528\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='preexperimentreportmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u53ef\u7528\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='processmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u53ef\u7528\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='projectprogressdetailmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u53ef\u7528\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='qualityinspectionreportmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u53ef\u7528\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='samplemodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u53ef\u7528\u72b6\u6001'),
        ),
    ]
