# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0010_auto_20170831_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='take_sample_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u53d6\u6837\u7684\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='take_sample_time',
            field=models.TimeField(blank=True, null=True, verbose_name='\u53d6\u6837\u7684\u65f6\u95f4'),
        ),
    ]
