# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_provider', '0011_auto_20170911_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u7bb1')),
                ('email_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u90ae\u7bb1\u5bc6\u7801')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u624b\u673a')),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u8054\u7cfb\u65b9\u5f0f',
                'verbose_name_plural': '\u7cfb\u7edf\u8054\u7cfb\u65b9\u5f0f',
            },
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='accept_sample_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u6536\u6837\u7684\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='accept_sample_time',
            field=models.TimeField(blank=True, null=True, verbose_name='\u6536\u6837\u7684\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u6709\u53c2\u4e0e\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='system_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='service_provider.SystemContact', verbose_name='\u4e91\u751f\u7269'),
        ),
    ]
