# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0012_auto_20170914_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='users',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='accept_sample_time_confirm',
            field=models.BooleanField(default=False, verbose_name='\u6536\u6837\u65f6\u95f4\u786e\u8ba4'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='\u9879\u76ee\u5b8c\u6210\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='customer_id',
            field=models.TimeField(blank=True, null=True, verbose_name='\u5ba2\u6237id'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='service_provider_id',
            field=models.TimeField(blank=True, null=True, verbose_name='\u670d\u52a1\u5546id'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='shipment_enterprise_id',
            field=models.TimeField(blank=True, null=True, verbose_name='\u7269\u6d41id'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='take_sample_time_confirm',
            field=models.BooleanField(default=False, verbose_name='\u53d6\u6837\u65f6\u95f4\u786e\u8ba4'),
        ),
    ]
