# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0013_auto_20170914_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5ba2\u6237id'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='service_provider_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u670d\u52a1\u5546id'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='shipment_enterprise_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7269\u6d41id'),
        ),
    ]
