# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0015_newprocessmodel_newprocessstepmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6d41\u7a0b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u6d41\u7a0b',
                'verbose_name_plural': '\u6d41\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='NewProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6b65\u9aa4\u540d\u79f0')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65e5\u671f')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('cycle', models.IntegerField(blank=True, null=True, verbose_name='\u5468\u671f')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5907\u6ce8')),
                ('send_message', models.BooleanField(default=False, verbose_name='\u53d1\u9001\u77ed\u4fe1')),
                ('message_content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u77ed\u4fe1\u5185\u5bb9')),
                ('send_email', models.BooleanField(default=False, verbose_name='\u53d1\u9001\u90ae\u4ef6')),
                ('email_content', models.CharField(blank=True, max_length=10000, null=True, verbose_name='\u90ae\u4ef6\u5185\u5bb9')),
                ('yunbio', models.BooleanField(default=False, verbose_name='\u4e91\u751f\u7269')),
                ('customer', models.BooleanField(default=False, verbose_name='\u5ba2\u6237')),
                ('service_provider', models.BooleanField(default=False, verbose_name='\u670d\u52a1\u5546')),
                ('shipment_enterprise', models.BooleanField(default=False, verbose_name='\u7269\u6d41\u5546')),
                ('running', models.BooleanField(default=False, verbose_name='\u53ef\u8fd0\u884c')),
                ('complete', models.BooleanField(default=False, verbose_name='\u6b65\u9aa4\u5b8c\u6210')),
                ('active', models.BooleanField(default=True, verbose_name='\u53ef\u7528')),
                ('process_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_step', to='service_provider.NewProcess', verbose_name='\u6d41\u7a0b')),
            ],
            options={
                'verbose_name': '\u6d41\u7a0b\u6b65\u9aa4',
                'verbose_name_plural': '\u6d41\u7a0b\u6b65\u9aa4',
            },
        ),
    ]
