# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0017_projectmodel_new_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='accept_sample_time_confirm',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='accept_sample_finish',
            field=models.BooleanField(default=False, verbose_name='\u6536\u6837\u5b8c\u6210'),
        ),
    ]
