# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0018_auto_20170915_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='accept_sample_finish',
            new_name='accept_sample_complete',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='take_sample_complete',
            field=models.BooleanField(default=False, verbose_name='\u53d6\u6837\u6837\u5b8c\u6210'),
        ),
    ]
