# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0019_auto_20170915_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprocessstep',
            name='half_cycle_message_status',
            field=models.BooleanField(default=False, verbose_name='\u5468\u671f\u4e00\u534a\u7684\u6d88\u606f\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='newprocessstepmodel',
            name='half_cycle_message_status',
            field=models.BooleanField(default=False, verbose_name='\u5468\u671f\u4e00\u534a\u7684\u6d88\u606f\u72b6\u6001'),
        ),
    ]
