# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0020_auto_20170915_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u540d\u79f0')),
                ('addr', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5730\u5740')),
                ('date', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='\u65e5\u671f')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8')),
                ('yunbio_confirm', models.BooleanField(default=False, verbose_name='\u4e91\u751f\u7269\u786e\u8ba4')),
                ('customer_confirm', models.BooleanField(default=False, verbose_name='\u5ba2\u6237\u786e\u8ba4')),
                ('download', models.BooleanField(default=False, verbose_name='\u4e0b\u8f7d\u72b6\u6001')),
                ('active', models.BooleanField(default=True, verbose_name='\u53ef\u7528\u72b6\u6001')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='service_provider.ProjectModel', verbose_name='\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u62a5\u544a',
                'verbose_name_plural': '\u62a5\u544a',
            },
        ),
    ]
