# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0022_auto_20170920_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='homogenization',
            field=models.BooleanField(default=False, verbose_name='\u6837\u54c1\u5747\u8d28\u5316\u8bf4\u660e'),
        ),
    ]
