# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0023_auto_20170920_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9879\u76ee\u6807\u7b7e'),
        ),
    ]
