# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0024_projectmodel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogressdetailmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f'),
        ),
    ]
