# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0025_auto_20170925_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcontact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u540d\u79f0'),
        ),
    ]
