# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0026_systemcontact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formalexperimentreportmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='preexperimentreportmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectstatustitlemodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionreportmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='subprocessmodel',
            name='process',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='process',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='sampling_date',
        ),
        migrations.DeleteModel(
            name='FormalExperimentReportModel',
        ),
        migrations.DeleteModel(
            name='PreExperimentReportModel',
        ),
        migrations.DeleteModel(
            name='ProcessModel',
        ),
        migrations.DeleteModel(
            name='ProjectStatusTitleModel',
        ),
        migrations.DeleteModel(
            name='QualityInspectionReportModel',
        ),
        migrations.DeleteModel(
            name='SubProcessModel',
        ),
    ]
