# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0027_auto_20170928_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstatemodel',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectStateModel',
        ),
    ]
